package d.model.pojos;
// Generated 11/11/2017 16:03:44 by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer id;
     private String rut;
     private String nombre;
     private Integer fijo;
     private Integer celular;
     private String email;

    public Persona() {
    }

    public Persona(String rut, String nombre, Integer fijo, Integer celular, String email) {
       this.rut = rut;
       this.nombre = nombre;
       this.fijo = fijo;
       this.celular = celular;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getFijo() {
        return this.fijo;
    }
    
    public void setFijo(Integer fijo) {
        this.fijo = fijo;
    }
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


