package model_pojos;
// Generated 14/11/2017 10:00:37 by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private String cuil;
     private String nombre;
     private Integer fijo;
     private Integer celular;
     private String email;

    public Persona() {
    }

    public Persona(String cuil, String nombre, Integer fijo, Integer celular, String email) {
       this.cuil = cuil;
       this.nombre = nombre;
       this.fijo = fijo;
       this.celular = celular;
       this.email = email;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public String getCuil() {
        return this.cuil;
    }
    
    public void setCuil(String cuil) {
        this.cuil = cuil;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getFijo() {
        return this.fijo;
    }
    
    public void setFijo(Integer fijo) {
        this.fijo = fijo;
    }
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


