package Modelo;
// Generated 10/11/2017 12:15:48 by Hibernate Tools 4.3.1



/**
 * Tablaejemplo generated by hbm2java
 */
public class Tablaejemplo  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private int edad;

    public Tablaejemplo() {
    }

    public Tablaejemplo(String nombre, String apellido, int edad) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
    }

    public Tablaejemplo(Integer id) {
        this.id = id;
    }
   
    
    
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }




}


